Replace chrono with std::time
Minoru/minoru-fediverse-crawler pull request #295
Opened 2024-07-27 23:14 UTC by Salanoid

This commit replaces chrono::Duration with std::time::Duration.
Fix for issue: #294

2024-07-28 10:23 UTC, Minoru requested changes
That's a good start! I'm surprised to receive a PR less than a day after I filed an issue :)

There are a few more places where we use `chrono`. I suggest you remove `chrono` from Cargo.toml and follow the compilation failures to fix all the remaining usages.

2024-07-28 10:23 UTC, Minoru commented on src/time.rs
> +    };
The purpose of the random offset is to move the time slightly into the future *or the past*. This code doesn't do the latter, because negative offsets are turned into positive ones, so it only moves offsets into the future.

I'm not entirely sure, but it might be easier to do all the calculations in `i64` (with `checked_...` methods) and convert it back into `Duration` right before calculating the `final_time`. What do you think?

2024-07-28 10:25 UTC, Minoru commented
Sadly there are no end-to-end tests in this project, so you'll have to rely on carefulness in order to preserve the current behaviour.

There are a few unit tests, and a couple CI jobs; these should be green.

2024-07-29 11:27 UTC, Salanoid commented
Hi, I will reopen this pull request once I have finished the commits. Thank you so much for your feedback.

2024-07-29 12:57 UTC, Salanoid commented
I made an intermediate commit; I still kept chrono so that the return types remains DateTime<Utc>, and I think like this everything should work like before.
To completely remove chrono, we need to adapt the other places where chrono is used, as you mentioned at the beginning.

2024-08-07 19:45 UTC, Minoru reviewed
Apologies for the delayed review! I'm very pleased with how much dependencies we can remove thanks to this change. It seems there's one last arithmetic problem to fix, and then this is good to go :+1:

2024-08-07 19:45 UTC, Minoru commented on src/time.rs
> +    }
This looks wrong. The original formula is `now + fixed_offet + random_offset` (and `random_offset` can be negative). The new formula seem to be:
* for positive `random_offset`s: `now + fixed_offset + random_offset`
* for negative `random_offset`s: `now - (fixed_offset + (-random_offset))`. This part is wrong because it subtracts not just the random offset, but the fixed one too.

2024-08-12 08:06 UTC, Salanoid commented on src/time.rs
> +    }
Thank you for your review and feedback. You were absolutely right in pointing out the issue. I've addressed the problem in my latest commit, and it should now be resolved. Please let me know if there's anything else that needs attention.

2024-08-12 18:36 UTC, Minoru approved these changes
The algorithm looks correct to me :+1: But the code fails to build (small error with the `Result` type). While you're at it, can you please also run `cargo fmt`?

2024-08-12 18:36 UTC, Minoru commented on src/time.rs
> +        }
Isn't this the same as `fixed_offset.as_secs().checked_sub(random_offset.unsigned_abs() as u64)`?

2024-08-13 09:38 UTC, Salanoid commented on src/time.rs
> +        }
Yes, you are right about that. I made this change.

2024-08-13 09:40 UTC, Salanoid commented
> The algorithm looks correct to me 👍 But the code fails to build (small error with the `Result` type). While you're at it, can you please also run `cargo fmt`?

I did that too, but i think the error from cargo build was because of my mistakes in here:
time.rs line ~56 return type for `now_plus_offset_plus_random_from_range`
```
) -> Result<SystemTime> {
) -> anyhow::Result<SystemTime> {
```

2024-08-14 19:04 UTC, Minoru commented
Excellent work, thank you very much for this! :tada:

2024-08-14 19:04 UTC, merged